language: python
python:
  - "2.7"
#command to install dependencies
install:
    - "pip install -r requirements.min.txt"
#command to run tests
script: "python manage.py test"

before_script:
  - psql -c "CREATE USER user WITH PASSWORD 'password';" -U postgres
